[package]
name = "hello_slint"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"
wasm-bindgen = "0.2.100"

[build-dependencies]
slint-build = "1.8.0"

[lib]
crate-type = ["cdylib", "rlib"]
